version: '3'

services:
  database:
    image: postgres:14.1-alpine
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5431:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
