<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO5BMttK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO5BMttK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO5BMttK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO5BMttK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO5BMttK\App_KernelDevDebugContainer([
    'container.build_hash' => 'O5BMttK',
    'container.build_id' => '93938cce',
    'container.build_time' => 1676336203,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO5BMttK');
